### ISSUE TITLE
Milestone A – Tooltips 

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#430] opened 2015-01-23 07:17 UTC
@gsouvik :

This is the issue you will commit the work under. when you do git commit, the first comment specifies the issue number.
An issue is also viewed as a task.

Please read the wiki, Part 3 for more details. I invite you to read the rest also. 

Let me know if you have questions.

Thank you.

**Comment by gsouvik** [comment] 2015-01-25 08:09
Hello @FWAJL,
I need a bit of help. I've finished the milestone A on my local and now need to push it back to the github repo.
I did a "git branch" on my local and found that there's only one branch available to me and it's "dev". Should I make all my commits to this branch and then push it to live. I'm a newbie to git/github.
Also for your reference I cloned the repo at https://github.com/FWAJL/FieldWorkAssistantMVC.git when I started working.

Thanks

**Comment by FWAJL** [comment] 2015-01-25 20:57
Hello @gsouvik,

It is normal you have only one branch locally when you start. You need to create the feature branch you must work on locally and then push the updates to the same feature branch remotely.

Look at [this wiki part](https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/4.Git-branching-model). It explains what you need to do.
The most important part to remember to `git pull` before you code. It is important because otherwise you won't be able to push updates if you have one file that is more up-to-date on the remote branch. 

I'm pretty sure it will be the case for you. So save your work somewhere before  you pull the new branch and then make a Beyond Compare (very handy utility) to get your code back into the local branch. Then you'll be able to push.

I code daily and I almost merge daily the dev branch updates to the feature branches so `git pul`every time you open your IDE and are about to change a file.

If the wiki 4 is not clear, let me know.

Talk soon.

**Comment by gsouvik** [comment] 2015-01-26 07:33
@FWAJL 

Thank you for the information. That helped me a lot. I'll create a branch "feature_popup" and then push everything to it. Thanks again

**Comment by FWAJL** [comment] 2015-01-26 08:47
@gsouvik 

Good :) Let me know if you have issues.

**Comment by gsouvik** [comment] 2015-01-27 06:20
Hello @bsaiken @FWAJL 
I pushed the changes for the milestone A - tooltip for the active and inactive lists. Currently those are implemented only for the Project and Technician screens.
Please review and let me know if the solution looks good.
Thank you.

**Comment by FWAJL** [comment] 2015-01-27 07:34
@gsouvik @bsaiken 

We will sure do. Thank you for the work.

**Comment by gsouvik** [comment] 2015-01-30 17:00
@FWAJL @bsaiken 
Code re-organized and tooltip issue (double hover) is fixed, feature_popup branch is updated with the changes.
Thank you

**Comment by gsouvik** [comment] 2015-01-31 08:07
@bsaiken @FWAJL 
feature_popup branch updated, Config/tooltipandpopupstrings.xml removed

**Comment by FWAJL** [comment] 2015-02-02 05:30
@gsouvik @bsaiken 

Looks good to me.

**Comment by gsouvik** [comment] 2015-02-02 21:23
Hello @bsaiken @FWAJL 
I've added the Milestone B related codes and have pushed the feature_popup branch. The following functionality is added:
1) For delete actions in the list items a bootstrap confirm box is added.
2) The text for the confirm box is pulled from the xml file I created earlier as part of milestone A.
3) If there's no message defined for a section (e.g. technician or task) the system falls back to simple delete without the confirm box.

I'll be doing some more code cleanups tomorrow. Please review the frontend part and let me know your feedback.
Thank you.

**Comment by FWAJL** [comment] 2015-02-03 05:33
@gsouvik 

I like what you have done. It looks good to me. Please wait for @bsaiken's feedback before moving to next milestone. 

Keep up the good work.

Thank you.

**Comment by gsouvik** [comment] 2015-02-03 05:43
@FWAJL 
Thank you for the feedback. @bsaiken also shared a note related to this release. I'll implemented the rest of the points outlined there and commit the code later down the day.

Thank you.

**Comment by FWAJL** [comment] 2015-02-03 08:03
@bsaiken 

Can you share the note, please? Thanks.

**Comment by bsaiken** [comment] 2015-03-03 16:22
@FWAJL 
Tooltips not working in Safari.  They work as with "Title" attribute.
Tooltips work correctly (in Safari) on my local Host with the feature_popup branch.

**Comment by bsaiken** [comment] 2015-03-03 18:27
@gsouvik 
Please note the Safari bug I found and see if you can duplicate.
I could not find some of your more recent changes on feature_popup branch.  Please check after the recent merge.
Please use Issue #586 to submit any new tooltip work as it will help us track progress.
I have update the eLance documents with respect to progress tracking.  Please look at the new documents.

**Comment by gsouvik** [comment] 2015-03-03 18:48
@bsaiken 
You mean you are not seeing the second round of tooltip updates I committed yesterday on the "feature_popup" branch? Or are you reviewing on live branch where it was supposed to be merged? 

I just checked on my local feature_popup branch and all the tooltip points are working. I haven't pulled from yesterday as @FWAJL notified me a merge is in progress.

**Comment by bsaiken** [comment] 2015-03-03 19:08
@gsouvik 
I check the live branch and the feature_popup branch.
I just wanted to make sure no work was lost.
Are you able to test with Safari?  When I test with Safari, the Project > List All tooltips do not work - they appear as Titles.
![screen shot 2015-03-03 at 12 08 09 pm](https://cloud.githubusercontent.com/assets/8228624/6470016/fbef7e00-c19d-11e4-9e2c-b2bd6f80bd46.png)

**Comment by gsouvik** [comment] 2015-03-03 19:22
@bsaiken 
Here are my findings:

On the live branch (http://dev.fieldworkmanager.com) :
NOT a single tooltip update is available. The reason you see those as in the screenshot, because those are basically the titles which were added initially to demo the UI and NOT the functional tooltip.

On MY LOCAL "feature_popup":
The complete tooltip work is up and working as per my release report yesterday. Tested on FF, Chrome and Safari.

"feature_popup" on GITHUB:
I'm not sure, as I'm afraid to do a pull and check the status as I might mess my local healthy copy.

@bsaiken @FWAJL Please suggest how we should proceed from here. I can confirm, on my local, all the points related to the tooltip are completely functional as per my release note yesterday. The commit hash was "273df3cb26190c00d4ba47fa767755baa2ab4090" as per git log on my local.

**Comment by bsaiken** [comment] 2015-03-03 19:40
@gsouvik @FWAJL 
It is possible Jeremie has not done the merge and release yet.
I do unit testing on Monday or Tuesday morning, and if things are not there that should be, I put up the red flag.  It should all be sorted out by tomorrow morning.

Did you notice on the update file that I added some items?

**Comment by gsouvik** [comment] 2015-03-03 19:52
@bsaiken 
Yes, I noticed you have added 13a and 14a for the tooltips section. I'll code those once this merge issue gets resolved.
Thank you.

**Comment by FWAJL** [comment] 2015-03-04 05:28
@bsaiken @gsouvik 

I was performing a merge from dev to feature_popup. It was completed yesterday evening @ GMT+1.

I have checked and all the popups are showing except maybe the task locations (not done yet? items 13a and 14a).

Please `git pull`. Thank you.

**Comment by FWAJL** [comment] 2015-03-04 06:11
@bsaiken 

Since there is 2 items left to do, we'll release it next time. I will release the items done.

Thank you.

**Closed** 2015-03-12 21:30 UTC
Labels: version:1.6.9
